"""schema inicial

Revision ID: 2e4fae625fbf
Revises: 
Create Date: 2026-08-05 12:59:02.765127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e4fae625fbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consentimento_marketing', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contato_email'), 'contato', ['email'], unique=False)
    op.create_table('disponibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADA', 'EXPIRADA', 'CANCELADA', name='statusreserva'), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('mp_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_data_hora'), 'reserva', ['data_hora'], unique=False)
    op.create_index(
        "unique_reserva_ativa",
        "reserva",
        ["servico_id", "data_hora"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDENTE', 'CONFIRMADA')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("unique_reserva_ativa", table_name="reserva")
    op.drop_index(op.f('ix_reserva_data_hora'), table_name='reserva')
    op.drop_table('reserva')
    op.drop_table('servico')
    op.drop_table('disponibilidade')
    op.drop_index(op.f('ix_contato_email'), table_name='contato')
    op.drop_table('contato')
    # ### end Alembic commands ###
